import crypto from "node:crypto";

export function quoteLiteral(value) {
  if (value === null || value === undefined) {
    return "NULL";
  }
  return `'${String(value).replace(/'/g, "''")}'`;
}

export function boolLiteral(value) {
  return value ? "TRUE" : "FALSE";
}

export function stableUuid(namespace, key) {
  const hex = crypto
    .createHash("sha1")
    .update(`${namespace}:${key}`)
    .digest("hex")
    .slice(0, 32);
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20, 32)}`;
}

export function sqlHeader(title) {
  return `-- ${title}\n-- Generated by scripts/seed-generator\nSET TIME ZONE 'UTC';\n\n`;
}
