#!/bin/bash

echo "💬 **ENHANCED COMMENT BACKFILL SCRIPT**"
echo "======================================"
echo ""

# Check if GITHUB_TOKEN is set
if [ -z "$GITHUB_TOKEN" ]; then
    echo "❌ GITHUB_TOKEN environment variable is not set"
    echo "   Please set it with: export GITHUB_TOKEN=your_token_here"
    exit 1
fi

echo "🔧 Compiling Comment Backfill Agents..."
mvn compile -q

if [ $? -ne 0 ]; then
    echo "❌ Compilation failed"
    exit 1
fi

echo "✅ Compilation successful"
echo ""

echo "📋 **COMMENT BACKFILL OPTIONS**"
echo "==============================="
echo ""
echo "Choose which backfill agent to run:"
echo ""
echo "1) 🚀 Simple Backfill Agent"
echo "   • Faster execution"
echo "   • Adds comments with search instructions for implementation issues"
echo "   • Recommended for quick backfill"
echo ""
echo "2) 🔍 Enhanced Backfill Agent"
echo "   • Searches for actual implementation issues"
echo "   • Includes direct links to frontend/backend issues when found"
echo "   • Takes longer but provides better comments"
echo ""
echo "3) 📊 Check Status Only"
echo "   • Shows how many issues were processed"
echo "   • Shows current backfill status"
echo "   • No comments added"
echo ""

read -p "Enter your choice (1-3): " choice

case $choice in
    1)
        echo ""
        echo "🚀 **SIMPLE BACKFILL AGENT SELECTED**"
        echo "====================================="
        echo ""
        echo "This will:"
        echo "  • Load processed issues from .github/orchestration/processed-issues.txt"
        echo "  • Add processing comments to all processed story issues"
        echo "  • Include search instructions for implementation issues"
        echo "  • Use 5 second delays between comments to prevent rate limits"
        echo ""
        
        read -p "Continue with Simple Backfill? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo "Cancelled by user"
            exit 0
        fi
        
        echo ""
        echo "🔄 Running Simple Comment Backfill Agent..."
        java -cp target/classes CommentBackfillAgent $GITHUB_TOKEN
        ;;
        
    2)
        echo ""
        echo "🔍 **ENHANCED BACKFILL AGENT SELECTED**"
        echo "======================================"
        echo ""
        echo "This will:"
        echo "  • Load processed issues from .github/orchestration/processed-issues.txt"
        echo "  • Search frontend and backend repositories for implementation issues"
        echo "  • Add processing comments with direct links when issues are found"
        echo "  • Use 5 second delays between comments to prevent rate limits"
        echo ""
        echo "⚠️  Note: This takes longer due to repository searches"
        echo ""
        
        read -p "Continue with Enhanced Backfill? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo "Cancelled by user"
            exit 0
        fi
        
        echo ""
        echo "🔄 Running Enhanced Comment Backfill Agent..."
        java -cp target/classes EnhancedCommentBackfillAgent $GITHUB_TOKEN
        ;;
        
    3)
        echo ""
        echo "📊 **CHECKING BACKFILL STATUS**"
        echo "==============================="
        echo ""
        
        if [ -f ".github/orchestration/processed-issues.txt" ]; then
            processed_count=$(wc -l < .github/orchestration/processed-issues.txt)
            echo "📂 Processed issues file found"
            echo "📊 Total processed issues: $processed_count"
            echo ""
            echo "📋 Recent processed issues:"
            tail -10 .github/orchestration/processed-issues.txt | while read issue; do
                echo "   • Issue #$issue"
            done
            echo ""
            echo "💡 To add comments to these issues, run this script again and choose option 1 or 2"
        else
            echo "❌ No processed issues file found at .github/orchestration/processed-issues.txt"
            echo "   This means no stories have been processed yet, or the file was moved/deleted"
        fi
        ;;
        
    *)
        echo "❌ Invalid choice. Please run the script again and choose 1, 2, or 3."
        exit 1
        ;;
esac

echo ""
echo "🏁 Comment backfill script complete!"
echo ""
echo "💡 **Tips:**"
echo "   • If some comments failed, you can run this script again to retry"
echo "   • The agents automatically handle rate limits and wait appropriately"
echo "   • Comments include links to coordination documents"
echo "   • All comments are marked as generated by the Durion Workspace Agent"