#!/bin/bash

echo "💬 **COMMENT BACKFILL SCRIPT**"
echo "============================="
echo ""

# Check if GITHUB_TOKEN is set
if [ -z "$GITHUB_TOKEN" ]; then
    echo "❌ GITHUB_TOKEN environment variable is not set"
    echo "   Please set it with: export GITHUB_TOKEN=your_token_here"
    exit 1
fi

echo "🔧 Compiling Comment Backfill Agent..."
mvn compile -q

if [ $? -ne 0 ]; then
    echo "❌ Compilation failed"
    exit 1
fi

echo "✅ Compilation successful"
echo ""

echo "🚀 Starting Comment Backfill Agent..."
echo "This will:"
echo "  1. Load the list of processed issues from .github/orchestration/processed-issues.txt"
echo "  2. Check which story issues are missing processing comments"
echo "  3. Add comments with proper rate limiting (5 seconds between comments)"
echo "  4. Handle secondary rate limits gracefully"
echo ""

read -p "Continue? (y/N): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Cancelled by user"
    exit 0
fi

echo ""
echo "🔄 Running Comment Backfill Agent..."
echo "=================================="

java -cp target/classes CommentBackfillAgent $GITHUB_TOKEN

echo ""
echo "🏁 Comment backfill script complete!"
echo ""
echo "💡 **Tips:**"
echo "   • If some comments failed, you can run this script again to retry"
echo "   • The script automatically handles rate limits and waits appropriately"
echo "   • Comments include links to implementation issues (when found)"
echo "   • All comments are marked as generated by the Comment Backfill Agent"